### ISSUE TITLE
Can we use the assembled contigs as input for this software? 

### ISSUE THREAD

**Issue by biofuture** [HubertTang/RdRpBin#1]
Hello, Hubert,

Thanks for developing this tool, since we have a lot samples, can we co-assemble all of them and then run this tool on the co-assembled contigs?

**Comment by HubertTang** [comment]
Hi,

Currently, RdRpBin is optimized for reads in some steps, and I am not sure if it can perform well on contigs. For example, in the second step, we use the SGA to calculate the overlap between test sequences to build the graph, but SGA is actually designed for reads. 

I will modify some of the steps and see if RdRpBin can be applied to contigs, and I will let you know when I get the results.

Best,
Xubo

**Comment by biofuture** [comment]
Thanks, Hubert

I have encountered errors while running the software with both contigs and fastq reads, it always reports the following errors, I am not sure why. It starts once the diamond alignment is finished.  Is this because my configuration of the software has problems?  I download the software and build the conda environment, and also download the database you have built for the tool. 

Thanks a lot for your prompt response.



/srv/scratch/z3524677/bashbin/miniconda3/envs/RdRpBin/lib/python3.8/site-packages/Bio/Seq.py:2979: BiopythonWarning: Partial codon, len(sequence) not a multiple of three. Explicitly trim the sequence or add trailing N before translation. This may become an error in future.
  warnings.warn(
sh: line 1: input_dir/test_rdrp_sim.csv.index.fasta.sga.prep: No such file or directory
Building index for input_dir/test_rdrp_sim.csv.index.fasta.sga.prep in memory using ropebwt
Error: could not open input_dir/test_rdrp_sim.csv.index.fasta.sga.prep for read
sh: line 1: input_dir/output.blastx.nucl.sga.prep: No such file or directory
Building index for input_dir/output.blastx.nucl.sga.prep in memory using ropebwt
Error: could not open input_dir/output.blastx.nucl.sga.prep for read
Error: could not open input_dir/output.blastx.nucl.sga.bwt for read

gzip: test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg.gz: unexpected end of file
Traceback (most recent call last):
  File "main.py", line 262, in <module>
    run_on_real(args = rdrpbin_args,
  File "main.py", line 165, in run_on_real
    graph_utils.run_prc(train_csv=f"{database_name}/data/train.csv", 
  File "/srv/scratch/z3524677/VIROME/RNAviruses_annotate/RdRpBin/graph_utils.py", line 44, in run_prc
    with open(sga_out) as test_f:
FileNotFoundError: [Errno 2] No such file or directory: 'input_dir/test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg'

**Comment by biofuture** [comment]
Command used is the following: 
python main.py input_dir/virome_contigs.all.fa -t 35

This is the folder for the data
tree input_dir/
input_dir/
|-- log
|   |-- blastx_mv
|   |   `-- prediction.csv
|   `-- prc
|-- output.blastx
|-- output.blastx.nucl
|-- output.blastx.prot
|-- test_rdrp_sim.csv
|-- test_rdrp_sim.csv.index.fasta
|-- test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg.gz
`-- virome_contigs.all.fa

3 directories, 8 files

**Comment by biofuture** [comment]
Thanks, Hubert,  

It works for fastq reads file now. But for the contigs file, it take ages to build a database in the sga step and produced a huge file of over 100 Gbs, (The contig file is 1.3 Gbs). 

I have one question,  how can I know the reads that I detected from different RNA viruses are not false positives? 

I put the reads assigned into blastx aligning with nr database, and get the annotation, the best hits are hypothetic protein or recombinase family protein.

**Comment by HubertTang** [comment]
Hi,

Given SGA is designed for reads, it may not work well on contigs. I will change the SGA to BLASTN later to build the edges between contigs and hope it can work.

To identify the false positive, maybe you can try using BLASTN to align the identified reads to the nt database directly.

Xubo

**Comment by HubertTang** [comment]
By the way, we are developing another tool to identify RNA viruses and works on contig. The preliminary experimental results on real data show that our tool can obtain higher recall while maintaining high precision on assembled contigs. if you don't mind, you can send us the contig data and we will test it for you and let you know the results. My email address is xubotang2-c@my.cityu.edu.hk

**Comment by biofuture** [comment]
Thanks, Hubert.  That's great news! Congrats on the better performance.   I have sent you the contig file by email.  Thank you for your help.
