### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by AlbertFreud** [HubertTang/RdRpBin#3]
Hi, Hubert,
Thanks for developing this greattool. I just want to use such tool to compare  the performance, acording to the README.md file. I create an input_dir and put my reads inside of the input_dir. And runing the RdRpBin just using the default parameters.
_python main.py input/test.fasta_
here is my test fasta file.
_>gi|58830|emb|X57540.1| DNA
GCGCCAGTCCTCCGATAGACTGAGTCGCCCGGGTACCCGTGTATCCAATAAACCCTCTTGCTGTTGCATCCGACTGGTGGTCTCGCTGTTCCTTGGGAGGGTCTCCTCAGAGTGATTGACTACCCGCCTCGGGGGTCTTTCATTTGGGGGCTCGTCCGGGATTCGGGGACCCCTGCCCAGGAACCACCGACCCACTATCGGGAGGTAAGCTGGCCAGCAACTGATCTGTGTCTGTCCGATTGTCCTGTGTTTATAACTGATCTTATGCGCCTGCGTCTGTACTAGTTGGCCGACTAGCTCTGTATCTGGCGGACCCGTGGTGGAACTGACGA_

then program reported:

index: input file is empty
Error: could not open output.blastx.nucl.sga.bwt for read

gzip: test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg.gz: unexpected end of file
Traceback (most recent call last):
  File "main.py", line 297, in <module>
    run_on_real(args = rdrpbin_args,
  File "main.py", line 192, in run_on_real
    graph_utils.run_prc(train_csv=f"{database_name}/data/train.csv", 
  File "/data1/RdRpBin/graph_utils.py", line 44, in run_prc
    with open(sga_out) as test_f:
FileNotFoundError: [Errno 2] No such file or directory: '/data1/RdRpBin/input/test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg'_

**Comment by HubertTang** [comment]
Hi Albert,

The reason for the error is because the program assumes that the input is a reads file (containing many reads) and that sga will build edges between the reads. If only one sequence is input or too few reads are input, sga cannot build edges, so this error is generated. I will add a warning here later.

Best,
Xubo

**Comment by AlbertFreud** [comment]
I am very appreciated your reply, Could you provide the lowest numbers the program needed?

**Comment by HubertTang** [comment]
It's hard to say. The sga can work properly only if the reads in the input reads file have overlapping. In other words, as long as the input file contains sequences that overlap each other, sga will work no matter how many sequences are input. A normal metagenomic data will contain reads that can overlap each other. If the SGA cannot build edges between reads, RdRpBin should skip sga and run GCN directly (I'm working on it).

**Comment by AlbertFreud** [comment]
Thank your reply, I noticed that  ICTV latest excel table contain  29 Order of RNA virus. However, you only model a total of 18 orders. Is that because database have limited data to train? 

_{ 'Ghabrivirales', 'Norzivirales', 'Wolframvirales', 'Cryppavirales', 'Jingchuvirales', 'Durnavirales', 'Goujianvirales', 'Ourlivirales', 'Articulavirales', 'Serpentovirales', 'Hepelivirales', 'Yadokarivirales', 'Mindivirales', 'Reovirales', 'Muvirales', 'Sobelivirales', 'Martellivirales', 'Picornavirales', 'Bunyavirales', 'Stellavirales', 'Patatavirales', 'Mononegavirales', 'Ortervirales', 'Tolivirales', 'Tymovirales', 'Nodamuvirales', 'Amarillovirales', 'Nidovirales', 'Timlovirales'}_

**Comment by HubertTang** [comment]
Yes, some orders have limited RdRps to train, so I discard them.

**Comment by AlbertFreud** [comment]
thank you very much :)
