### ISSUE TITLE
 line 262, in <module>     run_on_real(args = rdrpbin_args,

### ISSUE THREAD

**Issue by sunwanying21** [HubertTang/RdRpBin#4]
hi, Hubert,

I used "python main.py  -f fastq ~/path/RdRpBin-main/inout_dir/a.fq"  but I found the following results. could you please help me to solve it? Thank you very much. 
-----------------------------------------------------
480
490
Traceback (most recent call last):
  File "main.py", line 262, in <module>
    run_on_real(args = rdrpbin_args,
  File "main.py", line 174, in run_on_real
    graph_utils.get_prc_prot(reads_path=f"{work_dir}/test_rdrp_sim.csv.index.fasta", 
  File "/home/sunwanying/software/meta/RdRpBin-main/graph_utils.py", line 152, in get_prc_prot
    seq_utils.translate2protein(f"{temp_dir_path}/prc_seq.dna.fasta", True)
  File "/home/sunwanying/software/meta/RdRpBin-main/seq_utils.py", line 139, in translate2protein
    split_fasta(fasta_file=input_file_path, num_split=num_procr)
  File "/home/sunwanying/software/meta/RdRpBin-main/seq_utils.py", line 41, in split_fasta
    num_reads = int(subprocess.check_output("grep -c '^>' {}".format(fasta_file), shell=True).split()[0])
  File "/home/sunwanying/software/anaconda/01.bin/anaconda/envs/RdRpBin/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/sunwanying/software/anaconda/01.bin/anaconda/envs/RdRpBin/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'grep -c '^>' /home/sunwanying/software/meta/RdRpBin-main/input_dir/prc_temp/prc_seq.dna.fasta' returned non-zero exit status 1.

**Comment by HubertTang** [comment]
Hi,
How many sequences do you have in your 'a.fq' file? Can you help me check if the file ‘/home/sunwanying/software/meta/RdRpBin-main/input_dir/prc_temp/prc_seq.dna.fasta’ exists? If exists, does this file contain sequences or not?

**Comment by sunwanying21** [comment]
Hi, Hubert,
It's nearly 3 million reads and the "prc_seq.dna.fasta" is empty. 
And these are the files I got that are not empty.  Thank you.

log                          prc_temp
output.blastx                test_rdrp_sim.csv
output.blastx.nucl           test_rdrp_sim.csv.index.fasta
output.blastx.nucl.sga.bwt   test_rdrp_sim.csv.index.fasta.sga.bwt
output.blastx.nucl.sga.prep  test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg
output.blastx.nucl.sga.rbwt  test_rdrp_sim.csv.index.fasta.sga.prep
output.blastx.nucl.sga.rsai  test_rdrp_sim.csv.index.fasta.sga.rbwt
output.blastx.nucl.sga.sai   test_rdrp_sim.csv.index.fasta.sga.rsai
output.blastx.prot           test_rdrp_sim.csv.index.fasta.sga.sai

**Comment by HubertTang** [comment]
Hi,
Thanks for your detailed information.
I checked the code and the error may be brought by parsing some empty temporary files. I have fixed it, please try the latest version.

**Comment by sunwanying21** [comment]
Thanks for your reply. But I found another err on this(same command line). Could you please help me to look at it? Thank you. 
The temp_fimo_out and prc_temp/prc_seq.dna.fasta are empty. hmmer.tblout has some result. Can I use it? 

------------------------------------------------------------------------

480
490
Wrote 2973291 records to /home/sunwanying/software/meta/RdRpBin-main/input_dir/test_rdrp_sim.csv.index.fasta.0
Translate nucleic acid sequences
['M02266:193:000000000-KF3G2:1:1105:18563:4349_test_331294']
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
sh: 1: fimo: not found
Traceback (most recent call last):
  File "main.py", line 297, in <module>
    run_on_real(args = rdrpbin_args,
  File "main.py", line 237, in run_on_real
    motif_utils.run_fimo(motif_dir=f"{database_name}/motif",
  File "/home/sunwanying/software/meta/RdRpBin-main/motif_utils.py", line 56, in run_fimo
    for f in os.listdir(os.path.join(out_dir, order)):
FileNotFoundError: [Errno 2] No such file or directory: '/home/sunwanying/software/meta/RdRpBin-main/input_dir/temp_fimo_out/Amarillovirales'

**Comment by HubertTang** [comment]
It looks like it might be caused by the environment. I updated the “environment.yml”, please reinstall the environment and try RdRpBin on example/test.fasta to see if it works.

**Comment by sunwanying21** [comment]
Sorry, there are still some problems. Could you have a look again? Thank you.

Processing prc_seq.dna.fasta.47 ... ...
grep: /home/sunwanying/software/meta/RdRpBin-main/example/prc_temp/prc_seq.dna.fasta.47: No such file or directory
grep: /home/sunwanying/software/meta/RdRpBin-main/example/prc_temp/prc_seq.dna.fasta.45: No such file or directory
grep: /home/sunwanying/software/meta/RdRpBin-main/example/prc_temp/prc_seq.dna.fasta.43: No such file or directory
grep: grep: /home/sunwanying/software/meta/RdRpBin-main/example/prc_temp/prc_seq.dna.fasta.44/home/sunwanying/software/meta/RdRpBin-main/example/prc_temp/prc_seq.dna.fasta.46: No such file or directory: No such file or directory

100%|█████████████████| 1/1 [00:00<00:00, 778.31it/s]
.......
100%|█████████████████| 1/1 [00:00<00:00, 294.05it/s]
Traceback (most recent call last):
  File "main.py", line 297, in <module>
    run_on_real(args = rdrpbin_args,
  File "main.py", line 209, in run_on_real
    prc_out = graph_utils.get_prc_prot(reads_path=f"{work_dir}/test_rdrp_sim.csv.index.fasta", 
  File "/home/sunwanying/software/meta/RdRpBin-main/graph_utils.py", line 160, in get_prc_prot
    seq_utils.translate2protein(f"{temp_dir_path}/prc_seq.dna.fasta", True)
  File "/home/sunwanying/software/meta/RdRpBin-main/seq_utils.py", line 168, in translate2protein
    os.remove(f"{input_file_path}.{i}")
FileNotFoundError: [Errno 2] No such file or directory: '/home/sunwanying/software/meta/RdRpBin-main/example/prc_temp/prc_seq.dna.fasta.43'

**Comment by HubertTang** [comment]
Sorry for the late reply. To speed RdRpBin up, I added multi-threaded wrappers to each single-threaded tool. But I forget to consider the case when the actual number of threads exceeds the number of input sequences. I have fixed this issue, please try the latest version (no need to reinstall the environment).

**Comment by Rumakanta** [comment]
Dear Hubert Tang, 

Thanks for developing RdRpBin tool. I tried to use it, however couldn't succeed. I have exactly similar error as sunwanying21 commented on Jul 28. Let me know once it is resolved. Thanks

**Comment by HubertTang** [comment]
> Dear Hubert Tang,
> 
> Thanks for developing RdRpBin tool. I tried to use it, however couldn't succeed. I have exactly similar error as sunwanying21 commented on Jul 28. Let me know once it is resolved. Thanks

Sorry for the late reply. I tested the codes and this error should be resolved. May I ask how many sequences did you use?

With thanks,
Hubert
