### ISSUE TITLE
No such file or directory: 'test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg'

### ISSUE THREAD

**Issue by sunwanying21** [HubertTang/RdRpBin#5]
Hi, Hubert,

when I use " python main.py -f fasta  ~/software/meta/RdRpBin-main/test/scaffolds.fasta" to do the analysis. I encountered a problem. Could you please help me to figure it out? Thank you very much.

The "log/blastx_mv/prediction.csv" and "log/prc/" are empty.  there are the generated files. Thanks.

log
output.blastx
output.blastx.nucl
output.blastx.nucl.sga.prep
output.blastx.prot
scaffolds.fasta
test_rdrp_sim.csv
test_rdrp_sim.csv.index.fasta
test_rdrp_sim.csv.index.fasta.sga.bwt
test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg.gz
test_rdrp_sim.csv.index.fasta.sga.prep
test_rdrp_sim.csv.index.fasta.sga.rbwt
test_rdrp_sim.csv.index.fasta.sga.rsai
test_rdrp_sim.csv.index.fasta.sga.sai

-------------------------------------------------------------------------------------
Discarding sequences with ambiguous bases
Seed: 1658937747
Processing output.blastx.nucl

Preprocess stats:
Reads parsed:   0
Reads kept:     0 (-nan)
Reads failed primer screen:     0 (-nan)
Bases parsed:   0
Bases kept:     0 (-nan)
Number of incorrectly paired reads that were discarded: 0
[timer - sga preprocess] wall clock: 0.01s CPU: 0.00s
index: input file is empty
Error: could not open output.blastx.nucl.sga.bwt for read

gzip: test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg.gz: unexpected end of file
Traceback (most recent call last):
  File "main.py", line 297, in <module>
    run_on_real(args = rdrpbin_args,
  File "main.py", line 192, in run_on_real
    graph_utils.run_prc(train_csv=f"{database_name}/data/train.csv", 
  File "/home/sunwanying/software/meta/RdRpBin-main/graph_utils.py", line 44, in run_prc
    with open(sga_out) as test_f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/sunwanying/software/meta/RdRpBin-main/WHP5086/test_rdrp_sim.csv.index.fasta.sga.output.blastx.nucl.sga.asqg'

**Comment by HubertTang** [comment]
It seems that your input is contigs, but RdRpBin is developed for reads and it may not work on contigs. For example, in the second step, we use the SGA to calculate the overlap between test sequences to build the graph, but SGA is actually designed for reads and it may not work on contigs. This is probably the reason why SGA reports this error. If you want to try handling contig, please try another tool we are developing: VirBot (https://github.com/GreyGuoweiChen/RNA_virus_detector). It can identify the RNA viruses from assembled contigs.
